addons:
  apt:
    packages:
    - nodejs
language: python
sudo: false
python:
  - 3.5
  - 3.8
env:
  - TOX_ENV=django22
matrix:
  include:
    - python: 3.5
      env: TOX_ENV=csslint
    - python: 3.5
      env: TOX_ENV=eslint
    - python: 3.5
      env: TOX_ENV=pycodestyle
    - python: 3.5
      env: TOX_ENV=pylint
before_install:
  - "pip install -U pip"
  - export BOTO_CONFIG=/dev/null
cache:
    directories:
        - $HOME/.cache/pip
install:
  - "make requirements"
  - "pip install codecov"
script:
  - tox -e $TOX_ENV
branches:
    only:
      - master
after_success: codecov
