# Generated by Django 2.2.18 on 2021-04-06 15:23

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualtricsSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(db_index=True, help_text='The course block identifier.', max_length=255)),
                ('subscription_id', models.CharField(db_index=True, help_text='The subscription id from Qualtrics.', max_length=50)),
            ],
            options={
                'managed': True,
                'unique_together': {('course_id', 'usage_key', 'subscription_id')},
            },
        ),
    ]
