# Generated by Django 2.2.18 on 2021-04-20 18:46

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyStatus',
            fields=[
                ('user_id', models.IntegerField(db_index=True)),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(db_index=True, help_text='The course block identifier.', max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, help_text='The current completion status of the survey ', max_length=10)),
                ('grade', models.FloatField()),
                ('test', models.CharField(max_length=4)),
            ],
            options={
                'managed': True,
                'unique_together': {('usage_key', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='QualtricsSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(db_index=True, help_text='The course block identifier.', max_length=255)),
                ('subscription_id', models.CharField(db_index=True, help_text='The subscription id from Qualtrics.', max_length=50)),
            ],
            options={
                'managed': True,
                'unique_together': {('course_id', 'usage_key', 'subscription_id')},
            },
        ),
    ]
