# Generated by Django 2.2.18 on 2021-04-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualtricssurvey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveystatus',
            name='test',
        ),
    ]
