# Generated by Django 2.2.18 on 2021-04-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualtricssurvey', '0002_remove_surveystatus_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveystatus',
            name='grade',
            field=models.IntegerField(db_index=True),
        ),
    ]
