# Generated by Django 2.2.18 on 2021-04-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualtricssurvey', '0003_auto_20210420_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveystatus',
            name='grade',
        ),
    ]
